name: Build APK
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install deps
      run: cd frontend && npm install --legacy-peer-deps
    - name: Build
      run: cd frontend && npm run build
    - name: Capacitor setup
      run: cd frontend && npm install -g @capacitor/cli@5 --legacy-peer-deps
    - name: Cap add
      run: cd frontend && npx cap add android
    - name: Cap sync
      run: cd frontend && npx cap copy
    - name: Cap build
      run: cd frontend && npx cap build android
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: shopply.apk
        path: frontend/android/app/build/outputs/apk/debug/app-debug.apk
